# Generated by Django 5.1.3 on 2024-12-05 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_numero_puntuaciones_post_puntuacion_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puntuacion',
            name='puntuacion',
            field=models.PositiveIntegerField(help_text='De 1 a 5.', verbose_name='Puntuación'),
        ),
    ]
