# Generated by Django 5.1.3 on 2024-12-05 05:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_puntuacion_puntuacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ejercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del ejercicio')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción del ejercicio')),
                ('duracion', models.PositiveIntegerField(help_text='Duración aproximada del ejercicio', verbose_name='Duración (en minutos)')),
                ('repeticiones', models.PositiveIntegerField(help_text='Cantidad de repeticiones recomendadas', verbose_name='Número de repeticiones')),
                ('nivel_dificultad', models.CharField(choices=[('básico', 'Básico'), ('intermedio', 'Intermedio'), ('avanzado', 'Avanzado')], default='básico', max_length=50, verbose_name='Nivel de dificultad')),
                ('grupo_muscular', models.CharField(choices=[('piernas', 'Piernas'), ('brazos', 'Brazos'), ('espalda', 'Espalda'), ('pecho', 'Pecho'), ('core', 'Core'), ('completo', 'Cuerpo completo')], max_length=50, verbose_name='Grupo muscular principal')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ejercicio', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
            ],
            options={
                'verbose_name': 'Ejercicio',
                'verbose_name_plural': 'Ejercicios',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
