# Generated by Django 5.1.3 on 2024-12-05 05:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_ejercicio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del hábito')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción del hábito')),
                ('frecuencia', models.CharField(choices=[('diario', 'Diario'), ('semanal', 'Semanal'), ('mensual', 'Mensual')], default='diario', max_length=50, verbose_name='Frecuencia')),
                ('duracion_estimada', models.PositiveIntegerField(help_text='Tiempo estimado para realizar el hábito', verbose_name='Duración estimada (en minutos)')),
                ('importancia', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta')], default='media', max_length=50, verbose_name='Importancia del hábito')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habitos', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
            ],
            options={
                'verbose_name': 'Hábito',
                'verbose_name_plural': 'Hábitos',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
