# Generated by Django 5.1.3 on 2024-12-05 18:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_seguimientocomida'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consumidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre')),
                ('apellidos', models.CharField(max_length=255, verbose_name='Apellidos')),
                ('correo_electronico', models.EmailField(max_length=254, unique=True, verbose_name='Correo electrónico')),
                ('preferencias', models.TextField(blank=True, help_text='Describe las preferencias de contenido del consumidor, como temas de interés.', verbose_name='Preferencias')),
                ('registrado_en', models.DateTimeField(auto_now_add=True, verbose_name='Registrado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('usuario', models.OneToOneField(blank=True, help_text='Usuario autenticado asociado al consumidor.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consumidor', to=settings.AUTH_USER_MODEL, verbose_name='Usuario de Django')),
            ],
            options={
                'verbose_name': 'Consumidor',
                'verbose_name_plural': 'Consumidores',
                'ordering': ['registrado_en'],
            },
        ),
    ]
