# Generated by Django 5.1.3 on 2024-12-06 04:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_rutinaguardada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seguimientoejercicio',
            name='ejercicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos_ejercicio', to='blog.ejercicio', verbose_name='Ejercicio'),
        ),
        migrations.CreateModel(
            name='SeguimientoRutina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha de Seguimiento')),
                ('completado', models.BooleanField(default=False, verbose_name='¿Completado?')),
                ('ejercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos_rutina', to='blog.ejercicio', verbose_name='Ejercicio')),
                ('rutina_guardada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos_rutina', to='blog.rutinaguardada', verbose_name='Rutina Guardada')),
            ],
            options={
                'verbose_name': 'Seguimiento de Rutina',
                'verbose_name_plural': 'Seguimientos de Rutinas',
                'unique_together': {('rutina_guardada', 'fecha', 'ejercicio')},
            },
        ),
    ]
