# Generated by Django 5.1.3 on 2024-12-06 04:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_alter_seguimientoejercicio_ejercicio_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='seguimientorutina',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='seguimientorutina',
            name='comida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos_rutina', to='blog.alimentacion', verbose_name='Comida'),
        ),
        migrations.AddField(
            model_name='seguimientorutina',
            name='habito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos_rutina', to='blog.habito', verbose_name='Hábito'),
        ),
        migrations.AlterField(
            model_name='seguimientorutina',
            name='ejercicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos_rutina', to='blog.ejercicio', verbose_name='Ejercicio'),
        ),
        migrations.AlterField(
            model_name='seguimientorutina',
            name='rutina_guardada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos', to='blog.rutinaguardada', verbose_name='Rutina Guardada'),
        ),
        migrations.AlterUniqueTogether(
            name='seguimientorutina',
            unique_together={('rutina_guardada', 'fecha', 'ejercicio', 'comida', 'habito')},
        ),
    ]
