# Generated by Django 5.1.3 on 2024-12-06 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_alter_seguimientorutina_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaSemana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(choices=[('lunes', 'Lunes'), ('martes', 'Martes'), ('miercoles', 'Miércoles'), ('jueves', 'Jueves'), ('viernes', 'Viernes'), ('sabado', 'Sábado'), ('domingo', 'Domingo')], max_length=20, verbose_name='Día de la Semana')),
                ('rutina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dias', to='blog.rutina', verbose_name='Rutina')),
            ],
            options={
                'verbose_name': 'Día de la Semana',
                'verbose_name_plural': 'Días de la Semana',
                'unique_together': {('rutina', 'dia')},
            },
        ),
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ejercicio', 'Ejercicio'), ('comida', 'Comida'), ('habito', 'Hábito')], max_length=20, verbose_name='Tipo de Actividad')),
                ('referencia', models.PositiveIntegerField(verbose_name='ID de la Referencia')),
                ('completado', models.BooleanField(default=False, verbose_name='¿Completado?')),
                ('dia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='blog.diasemana', verbose_name='Día de la Semana')),
            ],
            options={
                'verbose_name': 'Actividad',
                'verbose_name_plural': 'Actividades',
            },
        ),
    ]
