# Generated by Django 5.1.3 on 2024-12-08 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_alter_post_publicado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rutina',
            name='descripcion',
        ),
    ]
